# Generated by Django 5.1.3 on 2024-11-29 07:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('stok', models.PositiveBigIntegerField(default=0)),
                ('harga_per_hari', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='project/motor')),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='rental.merek')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=10)),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_kembali', models.DateField()),
                ('jumlah_bayar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sudah_bayar', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DIPESAN', 'Dipesan'), ('DIPINJAM', 'Dipinjam'), ('DIKEMBALIKAN', 'Dikembalikan')], default='DIPESAN', max_length=20)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Perminjaman', to='rental.motor')),
            ],
        ),
    ]
