# Generated by Django 5.1.3 on 2024-12-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='motor',
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('stok', models.PositiveBigIntegerField(default=0)),
                ('harga_per_hari', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='project/kendaraan')),
                ('kategori', models.CharField(choices=[('MOTOR', 'Motor'), ('MOBIL', 'Mobil'), ('LAINNYA', 'Lainnya')], default='MOTOR', max_length=20)),
                ('kategori_promosi', models.CharField(choices=[('TERLARIS', 'Terlaris'), ('NEW', 'Baru'), ('DISKON', 'Diskon')], default='NEW', max_length=20)),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kendaraan', to='rental.merek')),
            ],
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='kendaraan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='rental.kendaraan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Motor',
        ),
    ]
