# Generated by Django 5.1.3 on 2024-12-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_peminjaman_motor_kendaraan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='kendaraan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='rental.kendaraan'),
        ),
    ]
