# Generated by Django 5.1.3 on 2024-12-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_kendaraan_harga_per_hari_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kendaraan',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='merek',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='harga_per_hari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='tahun',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='tipe',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='kendaraan_images/'),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='harga_promo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='kategori',
            field=models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor')], default='motor', max_length=20),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='merek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.merek'),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='promo_aktif',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='tidak_aktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='stok',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='merek',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='jumlah_bayar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='kendaraan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.kendaraan'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='nik',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('DIPINJAM', 'Dipinjam'), ('DIKEMBALIKAN', 'Dikembalikan')], default='DIPINJAM', max_length=20),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_kembali',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
